### ISSUE TITLE
Presentation notes

### ISSUE THREAD

**Issue by xintongqi** [Alex-XJK/NaiveBayes#8]
- introduction
- sequential (data generation + classifier)
- parallel
  - different par strategies
  - different number of cores (1, 2, 4, 8)
  - different data sizes (100, 10000, 100000). -> TBC
  - different validation method, i.e., different k values (1, 5, 10) -> TBC

**Comment by Alex-XJK** [comment]
The parallel testing is finished after f9aa12e
